import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 1 });
await page.goto(`https://allcaredc.kr/mission?cb=${Date.now()}`, { waitUntil: 'networkidle', timeout: 60000 });
const img = await page.$('.about-story-sub .about-figure img');
const box = await img.boundingBox();
const nat = await img.evaluate(el => ({ nw: el.naturalWidth, nh: el.naturalHeight, of: getComputedStyle(el).objectFit, op: getComputedStyle(el).objectPosition, ar: getComputedStyle(el).aspectRatio }));
console.log('rendered box', JSON.stringify(box));
console.log('displayed AR', (box.width/box.height).toFixed(3));
console.log('natural', nat.nw+'x'+nat.nh, 'AR', (nat.nw/nat.nh).toFixed(3));
console.log('css', JSON.stringify(nat));
await browser.close();
