import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
await page.goto(`https://allcaredc.kr/mission?cb=${Date.now()}`, { waitUntil: 'networkidle', timeout: 60000 });
const fig = await page.$('.about-story-sub .about-figure');
await fig.scrollIntoViewIfNeeded();
await page.waitForTimeout(1200);
await fig.screenshot({ path: '/tmp/shot_conti_fixed.png' });
console.log('saved');
await browser.close();
