# -*- coding: utf-8 -*-
"""백과사전 220 → 500+ 확장. 초성 자동 계산, 중복 스킵."""
import json

CHO = ["ㄱ","ㄲ","ㄴ","ㄷ","ㄸ","ㄹ","ㅁ","ㅂ","ㅃ","ㅅ","ㅆ","ㅇ","ㅈ","ㅉ","ㅊ","ㅋ","ㅌ","ㅍ","ㅎ"]
def initial(s):
    c = s[0]
    if '가' <= c <= '힣':
        return CHO[(ord(c) - ord('가')) // 588]
    return c.upper()

# (term, en, desc, treatment)
NEW = [
    # ── 임플란트 심화 ──
    ("임플란트 재수술","Implant Revision","실패한 임플란트를 제거하고 뼈를 회복시킨 뒤 다시 식립하는 치료입니다.","implant"),
    ("부러진 픽스처","Fractured Fixture","뼈 속에서 파절된 임플란트 몸체로, 전문적인 제거 수술이 필요합니다.","implant"),
    ("스크류 풀림","Screw Loosening","임플란트 보철을 고정하는 나사가 풀리는 현상으로 재조임 또는 교체로 해결합니다.","implant"),
    ("시멘트 유지형 보철","Cement-retained Prosthesis","접착제로 임플란트 보철을 고정하는 방식입니다.","implant"),
    ("나사 유지형 보철","Screw-retained Prosthesis","나사로 임플란트 보철을 고정해 탈착·수리가 용이한 방식입니다.","implant"),
    ("임플란트 1차 수술","First-stage Surgery","임플란트 픽스처를 잇몸뼈에 식립하는 첫 단계 수술입니다.","implant"),
    ("임플란트 2차 수술","Second-stage Surgery","뼈에 붙은 임플란트를 잇몸 위로 노출시키는 단계입니다.","implant"),
    ("발치 즉시 식립","Immediate Placement","발치와 동시에 임플란트를 심어 치료 기간을 줄이는 방법입니다.","implant"),
    ("골질","Bone Quality","임플란트 식립 부위 뼈의 단단한 정도로, 식립 계획에 영향을 줍니다.","implant"),
    ("골량","Bone Quantity","임플란트를 지지할 수 있는 뼈의 부피를 말합니다.","implant"),
    ("초기 고정","Primary Stability","식립 직후 임플란트가 뼈에 기계적으로 고정된 정도입니다.","implant"),
    ("상악동","Maxillary Sinus","위턱 어금니 위쪽의 빈 공간으로, 임플란트 시 거상술이 필요할 수 있습니다.","implant"),
    ("측방 접근 상악동 거상","Lateral Window Technique","측면 창을 내어 상악동 막을 들어 올리는 뼈이식 방법입니다.","implant"),
    ("치조정 접근 상악동 거상","Crestal Approach","식립 구멍을 통해 상악동 막을 들어 올리는 보존적 방법입니다.","implant"),
    ("자가골 이식","Autogenous Bone Graft","환자 본인의 뼈를 채취해 이식하는 방법입니다.","implant"),
    ("동종골","Allograft","사람 기증 뼈를 가공한 골이식재입니다.","implant"),
    ("이종골","Xenograft","동물 유래를 가공·정제한 골이식재입니다.","implant"),
    ("합성골","Synthetic Bone","인공적으로 합성한 골이식재입니다.","implant"),
    ("티타늄","Titanium","임플란트 몸체에 쓰이는 생체 친화적 금속입니다.","implant"),
    ("임플란트 표면처리","Surface Treatment","골유착을 촉진하기 위해 임플란트 표면을 가공하는 기술입니다.","implant"),
    ("토크","Torque","임플란트를 조이는 회전력 단위로 초기 고정 평가에 사용됩니다.","implant"),
    ("임플란트 식립 가이드","Surgical Guide","계획된 위치·각도로 식립하도록 돕는 수술 보조 장치입니다.","implant"),
    ("무절개 임플란트","Flapless Implant","잇몸 절개를 최소화하여 식립하는 방법입니다.","implant"),
    ("임시 임플란트","Provisional Implant","치료 기간 중 임시 보철을 지지하는 보조 임플란트입니다.","implant"),
    ("오버덴처","Overdenture","임플란트나 잔존 치근 위에 끼우는 탈착식 틀니입니다.","denture"),
    ("로케이터","Locator Attachment","임플란트 틀니를 연결하는 단추형 연결 장치입니다.","denture"),
    ("바 어태치먼트","Bar Attachment","임플란트들을 막대로 연결해 틀니를 고정하는 장치입니다.","denture"),
    ("임플란트 보험 적용","Implant Insurance","만 65세 이상 평생 2개까지 조건부 건강보험이 적용되는 제도입니다.","implant"),
    ("골결손부","Bone Defect","염증이나 발치로 뼈가 소실된 부위를 말합니다.","implant"),
    ("치조제 보존술","Ridge Preservation","발치 후 뼈 흡수를 줄이기 위해 발치와에 이식재를 채우는 술식입니다.","implant"),
    ("치조제 증대술","Ridge Augmentation","좁아진 잇몸뼈의 폭이나 높이를 늘리는 수술입니다.","implant"),
    ("임플란트 유지관리","Implant Maintenance","임플란트 주위 조직 건강을 위한 정기 점검과 세정 프로그램입니다.","implant"),
    # ── 교정 심화 ──
    ("어태치먼트(교정)","Attachment","투명교정 시 치아 이동을 돕기 위해 붙이는 작은 레진 돌기입니다.","ortho"),
    ("IPR","Interproximal Reduction","치아 사이를 미세하게 갈아 배열 공간을 확보하는 술식입니다.","ortho"),
    ("앵커리지","Anchorage","교정에서 치아 이동의 기준이 되는 고정원입니다.","ortho"),
    ("고무줄 걸기","Elastics","위아래 치아에 고무줄을 걸어 교합 관계를 개선하는 방법입니다.","ortho"),
    ("결찰","Ligation","교정용 철사를 브라켓에 고정하는 과정입니다.","ortho"),
    ("자가결찰 브라켓","Self-ligating Bracket","뚜껑 구조로 철사를 고정해 마찰을 줄인 브라켓입니다.","ortho"),
    ("투명 유지장치","Clear Retainer","교정 후 투명한 틀 형태로 착용하는 유지장치입니다.","ortho"),
    ("고정식 유지장치","Fixed Retainer","앞니 안쪽에 가는 철사를 접착해 유지하는 장치입니다.","ortho"),
    ("급속 구개 확장","Rapid Palatal Expansion","좁은 위턱을 넓히는 성장기 교정 장치 치료입니다.","ortho"),
    ("페이스 마스크","Face Mask","위턱 성장을 유도하는 성장기 악정형 장치입니다.","ortho"),
    ("트윈블록","Twin Block","아래턱 성장을 유도하는 기능성 교정 장치입니다.","ortho"),
    ("정중선 불일치","Midline Discrepancy","위아래 앞니 중심선이 어긋난 상태입니다.","ortho"),
    ("크로스바이트","Crossbite","일부 치아의 위아래 교합이 반대로 물리는 상태입니다.","ortho"),
    ("딥바이트","Deep Bite","위 앞니가 아래 앞니를 과도하게 덮는 교합입니다.","ortho"),
    ("오픈바이트","Open Bite","어금니는 물리는데 앞니가 닿지 않는 교합입니다.","ortho"),
    ("교정 발치","Extraction for Orthodontics","배열 공간 확보를 위해 소구치 등을 발치하는 결정입니다.","ortho"),
    ("재교정","Retreatment","교정 후 재배열되거나 결과 보완이 필요할 때 다시 하는 교정입니다.","ortho"),
    ("설측 버튼","Lingual Button","치아 안쪽에 붙여 고무줄을 거는 작은 장치입니다.","ortho"),
    ("교정용 왁스","Orthodontic Wax","장치가 점막을 찌를 때 임시로 덮는 보호 왁스입니다.","ortho"),
    ("치아 이동통","Tooth Movement Pain","장치 조정 후 며칠간 느껴지는 뻐근한 불편감입니다.","ortho"),
    ("블랙 트라이앵글","Black Triangle","치아 사이 잇몸이 채워지지 않아 생기는 삼각형 공간입니다.","ortho"),
    ("디본딩","Debonding","교정 종료 시 브라켓과 접착제를 제거하는 과정입니다.","ortho"),
    ("교정 정밀검사","Orthodontic Records","교정 진단을 위한 영상·모형·사진 종합 검사입니다.","ortho"),
    ("세팔로 분석","Cephalometric Analysis","측모 두부 방사선으로 골격을 계측·분석하는 방법입니다.","ortho"),
    # ── 보철·심미 심화 ──
    ("리튬 디실리케이트","Lithium Disilicate","투명도가 우수한 고강도 세라믹 보철 재료입니다.","esthetic"),
    ("풀 지르코니아","Full Zirconia","전체를 지르코니아로 제작한 고강도 크라운입니다.","esthetic"),
    ("프렙","Tooth Preparation","보철물을 씌우기 위해 치아를 다듬는 과정입니다.","esthetic"),
    ("마진","Margin","보철물과 치아가 만나는 경계선으로 정밀도가 중요합니다.","esthetic"),
    ("셰이드 매칭","Shade Matching","주변 치아와 보철물의 색을 맞추는 과정입니다.","esthetic"),
    ("트라이인","Try-in","최종 접착 전 보철물을 시적해 보는 단계입니다.","esthetic"),
    ("본딩","Bonding","보철물·레진을 치아에 화학적으로 접착하는 과정입니다.","esthetic"),
    ("비니어","Veneer","치아 앞면에 부착하는 얇은 세라믹 판으로 라미네이트와 같은 의미입니다.","esthetic"),
    ("다이아스테마","Diastema","앞니 사이가 벌어진 상태로 보철·교정으로 개선합니다.","esthetic"),
    ("왁스업","Wax-up","치료 결과를 미리 왁스 모형으로 만들어 보는 과정입니다.","esthetic"),
    ("목업","Mock-up","왁스업을 입안에 옮겨 미리 형태를 확인하는 과정입니다.","esthetic"),
    ("임시 접착","Temporary Cementation","경과 확인을 위해 보철물을 임시로 붙이는 방법입니다.","esthetic"),
    ("최종 접착","Definitive Cementation","확인이 끝난 보철물을 영구 접착하는 단계입니다.","esthetic"),
    ("교합 채득","Bite Registration","위아래 치아의 물림 관계를 기록하는 과정입니다.","esthetic"),
    ("핀레지","Pin-retained Restoration","핀을 이용해 수복물의 유지력을 높이는 방법입니다.","conservative"),
    ("실활치 미백","Non-vital Bleaching","신경치료 후 변색된 치아 내부를 미백하는 방법입니다.","whitening"),
    ("워킹 블리치","Walking Bleach","미백제를 치아 내부에 넣고 일정 기간 두는 실활치 미백법입니다.","whitening"),
    ("개인 트레이","Custom Tray","정밀한 본뜨기를 위해 개인 맞춤 제작한 트레이입니다.","esthetic"),
    ("러버 인상재","Rubber Impression Material","정밀 보철 제작에 쓰는 고무 성분 인상 재료입니다.","esthetic"),
    ("스캔 바디","Scan Body","임플란트 위치를 디지털로 기록하기 위한 스캔용 부품입니다.","implant"),
    # ── 보존·신경치료 심화 ──
    ("근관 충전","Canal Obturation","소독한 신경관을 충전재로 밀봉하는 신경치료 마지막 단계입니다.","conservative"),
    ("거타퍼차","Gutta-percha","근관 충전에 사용하는 생체 적합성 충전 재료입니다.","conservative"),
    ("근관장 측정","Working Length","신경관 길이를 측정해 치료 범위를 정하는 과정입니다.","conservative"),
    ("파일(근관치료)","Endodontic File","신경관 내부를 넓히고 다듬는 가는 기구입니다.","conservative"),
    ("니켈티타늄 파일","NiTi File","유연성이 높아 휜 신경관도 다듬을 수 있는 전동 파일입니다.","conservative"),
    ("MTA","Mineral Trioxide Aggregate","신경 보존·천공 수리에 쓰는 생체 친화적 시멘트입니다.","conservative"),
    ("치수 생활력 검사","Pulp Vitality Test","신경의 생존 여부를 확인하는 검사입니다.","conservative"),
    ("타진 검사","Percussion Test","치아를 가볍게 두드려 염증 여부를 확인하는 검사입니다.","conservative"),
    ("크랙 투스","Cracked Tooth","눈에 잘 보이지 않는 금이 간 치아로 씹을 때 통증이 특징입니다.","conservative"),
    ("치경부 마모증","Cervical Abrasion","잇몸 경계 치아가 패여 시린 증상을 유발하는 상태입니다.","conservative"),
    ("교모","Attrition","씹는 면이 마모되어 닳는 현상입니다.","conservative"),
    ("침식증","Erosion","산성 음식 등으로 치아가 녹는 현상입니다.","conservative"),
    ("2차 충치","Secondary Caries","기존 수복물 경계에 다시 생기는 충치입니다.","conservative"),
    ("초기 충치","Incipient Caries","법랑질 표면에 국한된 초기 단계 충치입니다.","conservative"),
    ("우식 위험도 평가","Caries Risk Assessment","개인별 충치 발생 위험을 평가해 예방 계획을 세우는 과정입니다.","conservative"),
    ("베이스(이장재)","Cavity Liner","깊은 충치 치료 시 신경 보호를 위해 까는 재료입니다.","conservative"),
    ("샌드위치 테크닉","Sandwich Technique","글래스아이오노머와 레진을 함께 쓰는 수복 방법입니다.","conservative"),
    ("코어 빌드업","Core Build-up","크라운을 씌우기 전 부족한 치아 구조를 보강하는 과정입니다.","conservative"),
    ("스톤 모형","Stone Model","본뜨기로 제작한 치아 석고 모형입니다.","conservative"),
    # ── 치주 심화 ──
    ("치주 검사","Periodontal Examination","잇몸 주머니 깊이 등을 측정해 치주 상태를 평가하는 검사입니다.","gum"),
    ("치주낭 측정","Pocket Probing","잇몸 주머니 깊이를 mm 단위로 측정하는 검사입니다.","gum"),
    ("치은연하 소파술","Subgingival Curettage","잇몸 속 염증 조직과 치석을 제거하는 치료입니다.","gum"),
    ("치근 분지부 병변","Furcation Involvement","어금니 뿌리 갈림 부위까지 진행된 치주염입니다.","gum"),
    ("각화치은","Keratinized Gingiva","치아 주위를 보호하는 단단한 잇몸 조직입니다.","gum"),
    ("유리치은 이식","Free Gingival Graft","입천장 조직을 떼어 부족한 잇몸에 이식하는 수술입니다.","gum"),
    ("결합조직 이식","Connective Tissue Graft","잇몸 퇴축 부위를 덮기 위한 연조직 이식술입니다.","gum"),
    ("치은압배","Gingival Retraction","정밀 본뜨기를 위해 잇몸을 일시적으로 벌리는 과정입니다.","gum"),
    ("골연하 결손","Infrabony Defect","치주염으로 뼈가 수직으로 파인 결손 형태입니다.","gum"),
    ("치주 재생술","Periodontal Regeneration","소실된 치주 조직의 재생을 유도하는 수술입니다.","gum"),
    ("에나멜 기질 유도체","Enamel Matrix Derivative","치주 조직 재생을 돕는 생체 재료입니다.","gum"),
    ("치주 유지관리","Periodontal Maintenance","치주 치료 후 재발 방지를 위한 정기 관리 프로그램입니다.","gum"),
    ("전악 치석제거","Full-mouth Scaling","입안 전체 치석을 제거하는 스케일링입니다.","gum"),
    ("초음파 스케일러","Ultrasonic Scaler","초음파 진동으로 치석을 제거하는 장비입니다.","gum"),
    ("수동 스케일러","Hand Scaler","손 기구로 미세한 치석을 제거하는 도구입니다.","gum"),
    ("출혈 지수","Bleeding Index","잇몸 출혈 정도를 수치화한 염증 지표입니다.","gum"),
    ("치면 세마","Tooth Polishing","치아 표면을 매끄럽게 연마해 치태 부착을 줄이는 과정입니다.","gum"),
    # ── 구강외과 심화 ──
    ("수평 매복","Horizontal Impaction","사랑니가 옆으로 누워 매복된 형태입니다.","surgery"),
    ("수직 매복","Vertical Impaction","사랑니가 똑바로 서 있으나 잇몸에 묻힌 형태입니다.","surgery"),
    ("완전 매복","Complete Impaction","뼈 속에 완전히 묻혀 있는 매복치입니다.","surgery"),
    ("치아 분할 발치","Tooth Sectioning","치아를 분할해 적은 손상으로 발치하는 방법입니다.","surgery"),
    ("봉합","Suture","절개 부위를 실로 꿰매 닫는 과정입니다.","surgery"),
    ("흡수성 봉합사","Resorbable Suture","시간이 지나면 녹아 제거가 필요 없는 봉합실입니다.","surgery"),
    ("지혈","Hemostasis","출혈을 멈추게 하는 처치입니다.","surgery"),
    ("하치조신경 손상","Inferior Alveolar Nerve Injury","아래턱 신경 손상으로 인한 감각 이상으로, 사전 영상 평가로 예방합니다.","surgery"),
    ("설신경","Lingual Nerve","혀의 감각을 담당하는 신경으로 사랑니 발치 시 주의 부위입니다.","surgery"),
    ("구강상악동 누공","Oroantral Fistula","발치 후 입과 상악동이 연결된 상태로 폐쇄 처치가 필요합니다.","surgery"),
    ("절개 배농","Incision and Drainage","고름집을 절개해 배농시키는 응급 처치입니다.","surgery"),
    ("봉와직염","Cellulitis","턱 주변으로 퍼진 급성 염증으로 신속한 치료가 필요합니다.","surgery"),
    ("조직검사","Biopsy","병소 조직을 떼어 현미경으로 진단하는 검사입니다.","surgery"),
    ("백반증","Leukoplakia","입안에 생기는 흰 반점으로 감별 진단이 필요한 병소입니다.","surgery"),
    ("편평태선","Lichen Planus","구강 점막에 그물 모양 병변이 생기는 만성 질환입니다.","surgery"),
    ("구내염","Stomatitis","입안 점막에 생기는 염증과 궤양의 총칭입니다.","surgery"),
    ("재발성 아프타","Recurrent Aphthous Ulcer","반복적으로 생기는 둥근 구내 궤양입니다.","surgery"),
    ("설소대 단축증","Ankyloglossia","혀 밑 인대가 짧아 혀 움직임이 제한되는 상태입니다.","surgery"),
    ("순소대","Labial Frenum","입술과 잇몸을 잇는 인대로 위치 이상 시 수술을 검토합니다.","surgery"),
    ("치성 감염","Odontogenic Infection","치아에서 시작되어 주변으로 퍼지는 감염입니다.","surgery"),
    ("악골 골절","Jaw Fracture","외상으로 턱뼈가 부러진 상태로 구강악안면외과에서 치료합니다.","surgery"),
    ("티타늄 플레이트","Titanium Plate","턱뼈 고정에 사용하는 금속판입니다.","surgery"),
    ("과잉치","Supernumerary Tooth","정상 개수보다 많이 생긴 치아로 발치를 검토합니다.","surgery"),
    ("치아종","Odontoma","치아 조직으로 구성된 양성 종양입니다.","surgery"),
    ("함치성 낭종","Dentigerous Cyst","매복치 주위에 생기는 낭종입니다.","surgery"),
    ("치근단 낭종","Radicular Cyst","치아 뿌리 끝 염증에서 비롯된 낭종입니다.","surgery"),
    ("골염","Osteitis","턱뼈에 생긴 염증입니다.","surgery"),
    ("약물 관련 턱뼈 괴사","MRONJ","골다공증 약 등과 관련된 턱뼈 괴사로 사전 약물 확인이 중요합니다.","surgery"),
    # ── 턱관절·수면 심화 ──
    ("측두하악관절","Temporomandibular Joint","머리뼈와 아래턱을 잇는 관절로 턱 운동을 담당합니다.","tmj"),
    ("관절원판 변위","Disc Displacement","관절원판이 제 위치를 벗어나 소리·통증을 유발하는 상태입니다.","tmj"),
    ("정복성 관절원판 변위","Disc Displacement with Reduction","입을 벌릴 때 원판이 제자리로 돌아오며 소리가 나는 유형입니다.","tmj"),
    ("비정복성 관절원판 변위","Disc Displacement without Reduction","원판이 돌아오지 않아 입벌림이 제한되는 유형입니다.","tmj"),
    ("측두근","Temporalis Muscle","관자놀이 부위 저작근으로 긴장 시 두통과 유사한 통증을 유발합니다.","tmj"),
    ("익돌근","Pterygoid Muscle","턱 깊은 곳의 저작근으로 턱관절 통증과 관련됩니다.","tmj"),
    ("개구량","Mouth Opening Range","입을 최대로 벌린 거리로 턱관절 평가 지표입니다.","tmj"),
    ("턱관절 탈구","TMJ Dislocation","입을 크게 벌린 뒤 다물어지지 않는 상태로 정복 처치가 필요합니다.","tmj"),
    ("야간 이갈이","Sleep Bruxism","수면 중 무의식적으로 이를 가는 습관입니다.","tmj"),
    ("주간 이악물기","Awake Clenching","깨어 있는 동안 이를 꽉 무는 습관입니다.","tmj"),
    ("근막통증증후군","Myofascial Pain Syndrome","저작근의 통증 유발점으로 인한 만성 통증 상태입니다.","tmj"),
    ("턱관절 자가관리","TMJ Self-care","온찜질·스트레칭 등 환자 스스로 하는 관리법입니다.","tmj"),
    ("전달마취","Block Anesthesia","신경 줄기 부위에 놓아 넓은 영역을 마취하는 방법입니다.","sleep"),
    ("침윤마취","Infiltration Anesthesia","치료 부위 주변에 직접 놓는 국소마취입니다.","sleep"),
    ("도포마취","Topical Anesthesia","주사 전 점막 표면에 바르는 마취제입니다.","sleep"),
    ("아산화질소 흡입진정","Nitrous Oxide Sedation","웃음가스를 흡입해 가볍게 이완시키는 진정법입니다.","sleep"),
    ("정맥진정","IV Sedation","정맥로로 진정제를 투여하는 의식하진정법입니다.","sleep"),
    ("미다졸람","Midazolam","의식하진정에 흔히 사용되는 진정 약물입니다.","sleep"),
    ("산소포화도 감시","Pulse Oximetry","진정 중 혈중 산소 농도를 지속 관찰하는 안전 장치입니다.","sleep"),
    ("회복실","Recovery Room","진정 후 안정을 취하며 회복하는 공간입니다.","sleep"),
    ("진정 전 평가","Pre-sedation Assessment","전신 상태·복용약을 확인하는 진정 전 안전 평가입니다.","sleep"),
    ("금식 지침","Fasting Guideline","진정 전 일정 시간 음식·물 섭취를 제한하는 안전 수칙입니다.","sleep"),
    # ── 틀니 심화 ──
    ("의치 안정제","Denture Adhesive","틀니 유지력을 보조하는 접착 크림입니다.","denture"),
    ("이장(릴라인)","Reline","틀니 내면을 다시 채워 잇몸에 맞추는 조정술입니다.","denture"),
    ("개상(리베이스)","Rebase","틀니 분홍 몸체 전체를 새로 바꾸는 수리입니다.","denture"),
    ("인공치","Artificial Teeth","틀니에 배열하는 인공 치아입니다.","denture"),
    ("클라스프","Clasp","부분틀니를 남은 치아에 거는 금속 고리입니다.","denture"),
    ("서베이드 크라운","Surveyed Crown","부분틀니 고리가 잘 걸리도록 설계된 크라운입니다.","denture"),
    ("의치성 구내염","Denture Stomatitis","틀니 아래 잇몸에 생기는 염증으로 위생 관리로 예방합니다.","denture"),
    ("플랜지","Flange","틀니 가장자리 날개 부분으로 유지력에 영향을 줍니다.","denture"),
    ("교합제","Occlusion Rim","틀니 제작 중 교합 높이를 정하는 왁스 틀입니다.","denture"),
    ("시적","Try-in Denture","완성 전 틀니 배열을 입안에서 확인하는 단계입니다.","denture"),
    ("즉시의치","Immediate Denture","발치 직후 바로 끼우는 임시 틀니입니다.","denture"),
    ("금속상 틀니","Metal-based Denture","입천장 부분을 얇은 금속으로 만든 틀니입니다.","denture"),
    ("탄성의치","Flexible Denture","유연한 재질로 만들어 금속 고리가 없는 부분틀니입니다.","denture"),
    # ── 예방·소아·일반 ──
    ("정기 구강검진","Regular Check-up","질환을 조기에 발견하기 위한 주기적 검진입니다.","conservative"),
    ("구강위생 교육","Oral Hygiene Instruction","개인별 칫솔질·치실 사용법을 교육하는 과정입니다.","gum"),
    ("바스법","Bass Technique","잇몸 경계에 칫솔모를 45도로 대고 진동시키는 칫솔질법입니다.","gum"),
    ("회전법","Rolling Technique","잇몸에서 치아 방향으로 쓸어내리는 칫솔질법입니다.","gum"),
    ("전동칫솔","Electric Toothbrush","진동·회전으로 치태 제거를 돕는 칫솔입니다.","gum"),
    ("워터픽","Water Flosser","물줄기로 치아 사이를 세척하는 구강 세정기입니다.","gum"),
    ("혀클리너","Tongue Cleaner","설태를 제거해 입냄새를 줄이는 도구입니다.","gum"),
    ("가글액","Mouthwash","구강 세균을 줄이는 보조 세정제입니다.","gum"),
    ("클로르헥시딘","Chlorhexidine","치과에서 처방하는 항균 가글 성분입니다.","gum"),
    ("자일리톨","Xylitol","충치균 활동을 억제하는 천연 감미료입니다.","conservative"),
    ("불소치약","Fluoride Toothpaste","법랑질을 강화해 충치를 예방하는 치약입니다.","conservative"),
    ("치아 홈 메우기","Pit and Fissure Sealant","어금니 골짜기를 메워 충치를 예방하는 실란트의 다른 이름입니다.","conservative"),
    ("우유병 우식증","Baby Bottle Caries","수유 습관과 관련된 유아기 다발성 충치입니다.","conservative"),
    ("유치 발치","Primary Tooth Extraction","흔들리거나 문제가 있는 젖니를 빼는 처치입니다.","surgery"),
    ("맹출 장애","Eruption Disturbance","치아가 제때 나오지 못하는 상태입니다.","ortho"),
    ("선천 결손치","Congenitally Missing Tooth","태어날 때부터 치아 싹이 없는 경우입니다.","implant"),
    ("왜소치","Microdontia","정상보다 작게 형성된 치아입니다.","esthetic"),
    ("치아 끼임","Food Impaction","치아 사이에 음식물이 끼는 증상으로 원인 치료가 필요합니다.","conservative"),
    ("구강건조증","Xerostomia","침 분비가 줄어 입이 마르는 증상입니다.","gum"),
    ("구강작열감","Burning Mouth Syndrome","입안이 화끈거리는 만성 감각 이상입니다.","tmj"),
    ("입냄새 측정","Halimeter Test","구취 원인 가스를 측정하는 검사입니다.","gum"),
    # ── 진단·장비·디지털 ──
    ("콘빔CT","CBCT","치과용 3차원 CT로 뼈·신경 위치를 입체적으로 확인합니다.","implant"),
    ("구강스캐너","Intraoral Scanner","본뜨기 없이 치아를 3D 스캔하는 디지털 장비입니다.","esthetic"),
    ("3D 프린팅","3D Printing","수술 가이드·모형 등을 출력하는 디지털 제작 기술입니다.","implant"),
    ("디지털 교합 분석","Digital Occlusal Analysis","씹는 힘 분포를 디지털로 측정하는 검사입니다.","tmj"),
    ("치근단 촬영","Periapical Radiograph","치아 1~2개를 정밀하게 보는 소형 방사선 사진입니다.","conservative"),
    ("교익 촬영","Bitewing Radiograph","치아 사이 충치 확인에 유용한 촬영법입니다.","conservative"),
    ("파노라마 촬영","Panoramic Radiograph","턱 전체를 한 장에 담는 기본 방사선 검사입니다.","implant"),
    ("방사선 방어","Radiation Protection","납 방어복 등으로 방사선 노출을 최소화하는 수칙입니다.","conservative"),
    ("구강 카메라","Intraoral Camera","입안 상태를 화면으로 보여주는 소형 카메라입니다.","conservative"),
    ("치과용 현미경","Dental Microscope","미세 근관치료 등에 사용하는 고배율 현미경입니다.","conservative"),
    ("레이저 치료","Dental Laser","연조직 처치·살균 등에 활용하는 레이저 장비입니다.","gum"),
    ("전기 치수검사","Electric Pulp Test","미세 전류로 신경 생활력을 확인하는 검사입니다.","conservative"),
    ("멸균 소독 시스템","Sterilization System","기구를 고압 증기 등으로 멸균하는 감염관리 체계입니다.","surgery"),
    ("에어샤워","Air Shower","수술실 입장 전 공기로 먼지를 제거하는 감염관리 설비입니다.","surgery"),
    ("개인 맞춤 트레이","Custom Impression Tray","정밀 인상을 위해 환자 맞춤 제작한 본뜨기 틀입니다.","denture"),
    ("기공물","Dental Lab Work","기공실에서 제작하는 보철물·장치의 총칭입니다.","esthetic"),
    ("원내 기공실","In-house Dental Lab","병원 안에 기공사가 상주하는 제작 시설로 빠른 조정이 가능합니다.","esthetic"),
    ("캐드캠 밀링","CAD/CAM Milling","디지털 설계로 보철물을 깎아 제작하는 방식입니다.","esthetic"),
    # ── 증상·기타 ──
    ("시린이","Tooth Sensitivity","찬 자극에 치아가 짜릿한 증상으로 원인별 치료가 다릅니다.","conservative"),
    ("욱신거림","Throbbing Pain","맥박처럼 욱신거리는 통증으로 신경 염증을 시사할 수 있습니다.","conservative"),
    ("자발통","Spontaneous Pain","자극 없이 저절로 생기는 통증으로 진행된 치수염의 신호입니다.","conservative"),
    ("야간통","Nocturnal Pain","밤에 심해지는 치통으로 치수염 감별이 필요합니다.","conservative"),
    ("방산통","Referred Pain","원인 치아와 다른 부위에서 느껴지는 통증입니다.","tmj"),
    ("치은 증식","Gingival Hyperplasia","약물 등으로 잇몸이 과도하게 자라는 상태입니다.","gum"),
    ("치아 착색","Tooth Staining","음식·흡연 등으로 치아 표면에 색이 배는 현상입니다.","whitening"),
    ("테트라사이클린 변색","Tetracycline Staining","항생제 영향으로 생긴 회색조 변색입니다.","whitening"),
    ("불소증","Fluorosis","과량 불소로 법랑질에 흰 반점이 생긴 상태입니다.","whitening"),
    ("법랑질 형성부전","Enamel Hypoplasia","법랑질이 불완전하게 형성된 상태입니다.","esthetic"),
    ("치아 매복","Tooth Impaction","치아가 뼈나 잇몸에 묻혀 나오지 못한 상태입니다.","surgery"),
    ("유착치","Ankylosed Tooth","치아가 뼈와 직접 붙어 움직이지 않는 상태입니다.","ortho"),
    ("이소맹출","Ectopic Eruption","치아가 정상 위치를 벗어나 나는 현상입니다.","ortho"),
    ("치간 이개술","Tooth Separation","치아 사이를 일시적으로 벌리는 술식입니다.","conservative"),
    ("교합성 외상","Occlusal Trauma","과도한 교합력으로 치주 조직이 손상되는 상태입니다.","gum"),
    ("긴장성 두통","Tension Headache","저작근 긴장과 관련될 수 있는 두통 유형입니다.","tmj"),
    ("연하곤란","Dysphagia","삼키기 어려운 증상으로 구강 기능 평가가 필요할 수 있습니다.","denture"),
    ("저작 효율","Masticatory Efficiency","음식을 씹어 부수는 능력의 지표입니다.","denture"),
    ("발음 적응","Phonetic Adaptation","틀니·교정장치 착용 후 발음에 익숙해지는 과정입니다.","denture"),
    ("심미 분석","Esthetic Analysis","얼굴·입술·치아 비율을 분석해 심미 치료를 설계하는 과정입니다.","esthetic"),
    ("골격성 부정교합","Skeletal Malocclusion","턱뼈 위치 이상에서 비롯된 부정교합입니다.","ortho"),
    ("치성 부정교합","Dental Malocclusion","치아 배열 이상에서 비롯된 부정교합입니다.","ortho"),
    ("전치부 외상","Anterior Tooth Trauma","넘어짐 등으로 앞니가 다친 외상입니다.","surgery"),
    ("치아 파편 재부착","Fragment Reattachment","부러진 치아 조각을 다시 붙이는 치료입니다.","conservative"),
    ("스플린팅(치아고정)","Tooth Splinting","흔들리는 치아를 옆 치아와 묶어 고정하는 처치입니다.","gum"),
    ("자가치아 이식","Autotransplantation","본인의 치아(주로 사랑니)를 빈자리에 옮겨 심는 수술입니다.","surgery"),
    ("의도적 재식술","Intentional Replantation","치아를 빼서 처치 후 다시 심는 치료입니다.","conservative"),
    ("치근 절제술","Root Resection","여러 뿌리 중 문제 뿌리만 제거하는 수술입니다.","gum"),
    ("편측 저작","Unilateral Chewing","한쪽으로만 씹는 습관으로 턱관절·치아에 부담을 줍니다.","tmj"),
    ("구호흡","Mouth Breathing","입으로 숨 쉬는 습관으로 구강 건조와 부정교합의 원인이 됩니다.","ortho"),
    ("손가락 빨기","Thumb Sucking","장기화되면 앞니 돌출 등 부정교합을 유발하는 습관입니다.","ortho"),
    ("혀 내밀기 습관","Tongue Thrusting","삼킬 때 혀로 앞니를 미는 습관으로 개방교합과 관련됩니다.","ortho"),
    ("악습관 차단 장치","Habit Breaker","구강 악습관을 차단하는 교정 보조 장치입니다.","ortho"),
    ("기능성 반대교합","Functional Crossbite","턱 위치 변화로 생긴 반대교합으로 조기 개선이 유리합니다.","ortho"),
    ("터너 치아","Turner's Tooth","유치 염증이 영구치 형성에 영향을 준 변색·결함 치아입니다.","esthetic"),
    ("신생선","Neonatal Line","출생 전후 형성된 법랑질 성장선입니다.","conservative"),
    ("제3대구치","Third Molar","사랑니의 정식 명칭입니다.","surgery"),
    ("제2대구치","Second Molar","사랑니 앞 큰어금니입니다.","conservative"),
    ("제1대구치","First Molar","6세경 나는 첫 영구 어금니로 평생 교합의 기준이 됩니다.","conservative"),
    ("측절치","Lateral Incisor","중절치 옆 앞니입니다.","esthetic"),
    ("중절치","Central Incisor","정중앙 앞니로 심미의 핵심 치아입니다.","esthetic"),
    ("치식","Tooth Numbering","치아 위치를 숫자로 표기하는 체계입니다.","conservative"),
    ("FDI 표기법","FDI Notation","국제 표준 치아 번호 표기법입니다.","conservative"),
    ("교합기","Articulator","턱 움직임을 재현해 보철물을 제작하는 기공 장비입니다.","esthetic"),
    ("페이스보우","Facebow","턱관절 기준으로 상악 위치를 기록하는 장치입니다.","esthetic"),
    ("센트릭","Centric Relation","하악의 기준 위치로 보철·교합 치료의 출발점입니다.","esthetic"),
    ("가이드 교합","Anterior Guidance","앞니가 턱 운동을 유도하는 교합 방식입니다.","esthetic"),
    ("균형 교합","Balanced Occlusion","틀니에서 양측이 고르게 닿도록 설계한 교합입니다.","denture"),
    ("조기 접촉","Premature Contact","일부 치아가 먼저 닿아 교합을 방해하는 접촉점입니다.","tmj"),
    ("교합 간섭","Occlusal Interference","턱 운동을 방해하는 비정상 접촉입니다.","tmj"),
    ("프리미엄 임플란트","Premium Implant","장기 임상 데이터를 갖춘 글로벌 브랜드 임플란트를 이르는 말입니다.","implant"),
    ("국산 임플란트","Domestic Implant","국내 제조 임플란트로 임상 신뢰도가 확보된 제품군입니다.","implant"),
    ("멤브레인","Membrane","골이식 부위를 덮어 재생을 유도하는 차폐막입니다.","implant"),
    ("티슈 펀치","Tissue Punch","무절개 식립 시 잇몸을 원형으로 제거하는 기구입니다.","implant"),
    ("커버 스크류","Cover Screw","1차 수술 후 임플란트 상단을 덮는 보호 나사입니다.","implant"),
    ("임프레션 코핑","Impression Coping","임플란트 위치를 본뜨기로 옮기는 부품입니다.","implant"),
    ("어버트먼트 스크류","Abutment Screw","어버트먼트를 픽스처에 고정하는 나사입니다.","implant"),
    ("맞춤형 어버트먼트","Custom Abutment","환자 잇몸 형태에 맞춰 제작한 연결 기둥입니다.","implant"),
    ("티타늄 베이스","Ti-base","지르코니아 보철과 임플란트를 연결하는 티타늄 부품입니다.","implant"),
    ("프로비저널","Provisional Restoration","최종 보철 전 사용하는 임시 보철물입니다.","esthetic"),
    ("이머전스 프로파일","Emergence Profile","잇몸에서 보철물이 올라오는 형태로 심미에 중요합니다.","implant"),
    ("핑크 포세린","Pink Porcelain","잇몸 색을 재현하는 도재로 심미 보완에 사용합니다.","esthetic"),
    ("림 처짐","Ridge Resorption","발치 후 잇몸뼈가 흡수되어 낮아지는 현상입니다.","denture"),
    ("플리퍼","Flipper","앞니 빈자리를 임시로 채우는 간이 틀니입니다.","denture"),
    ("마우스가드","Mouthguard","운동 중 치아·턱 손상을 막는 보호 장치입니다.","tmj"),
    ("스포츠 치의학","Sports Dentistry","운동 관련 구강 외상 예방·치료 분야입니다.","surgery"),
    ("금연 상담","Smoking Cessation Counseling","구강 건강을 위한 금연 지원 상담입니다.","gum"),
    ("타액선","Salivary Gland","침을 분비하는 샘으로 구강 건강에 중요한 역할을 합니다.","surgery"),
    ("타석증","Sialolithiasis","침샘 관에 돌이 생겨 붓고 아픈 질환입니다.","surgery"),
    ("이하선","Parotid Gland","귀 앞쪽의 가장 큰 침샘입니다.","surgery"),
    ("악하선","Submandibular Gland","턱 아래 침샘으로 타석이 잘 생기는 부위입니다.","surgery"),
    ("구강암 검진","Oral Cancer Screening","구강 점막을 정기적으로 살펴 조기 발견하는 검진입니다.","surgery"),
    ("HPV와 구강","HPV in Oral Cavity","일부 구인두암과 관련이 알려진 바이러스입니다.","surgery"),
    ("방사선 치료 후 구강관리","Post-radiation Oral Care","방사선 치료 환자의 구강건조·충치 예방 관리입니다.","conservative"),
    ("항응고제와 발치","Anticoagulants in Extraction","피를 묽게 하는 약 복용자의 발치 전 확인 사항입니다.","surgery"),
    ("비스포스포네이트","Bisphosphonate","골다공증 약 성분으로 턱뼈 수술 전 확인이 필요합니다.","surgery"),
    ("임산부 치과진료","Dental Care in Pregnancy","임신 중기 중심으로 안전하게 진행하는 치과 진료 원칙입니다.","conservative"),
    ("소아 진정치료","Pediatric Sedation","협조가 어려운 어린이를 위한 진정 하 치료입니다.","sleep"),
    ("행동 조절","Behavior Management","어린이 치과 공포를 줄이는 심리적 접근법입니다.","sleep"),
    ("티엘 검사","Tell-Show-Do","설명-시연-시행 순서로 아이의 불안을 줄이는 기법입니다.","sleep"),
    ("치과 공포증","Dental Phobia","치과 치료에 대한 과도한 불안으로 진정법이 도움이 됩니다.","sleep"),
    ("화이트 스폿","White Spot Lesion","법랑질 초기 탈회로 생긴 흰 반점입니다.","ortho"),
    ("레진 침투법","Resin Infiltration","화이트 스폿에 레진을 침투시켜 개선하는 치료입니다.","esthetic"),
    ("치아 우식 활성검사","Caries Activity Test","충치 유발 세균 활성도를 측정하는 검사입니다.","conservative"),
    ("치면 착색제","Disclosing Agent","치태를 물들여 칫솔질 상태를 확인하는 약제입니다.","gum"),
    ("전문가 치면세정","Professional Mechanical Tooth Cleaning","전문 기구로 치태·착색을 제거하는 관리입니다.","gum"),
    ("치은열구액","Gingival Crevicular Fluid","잇몸 틈새에서 나오는 체액으로 염증 지표가 됩니다.","gum"),
    ("바이오필름","Biofilm","치아 표면에 형성되는 세균막으로 치태의 본질입니다.","gum"),
    ("치주병원균","Periodontal Pathogen","치주염을 일으키는 주요 세균군입니다.","gum"),
    ("구강 마이크로바이옴","Oral Microbiome","입안에 사는 미생물 생태계 전체를 이르는 말입니다.","gum"),
    ("전신질환과 치주","Systemic Disease and Periodontitis","당뇨·심혈관 질환과 잇몸병의 연관성을 다루는 영역입니다.","gum"),
    ("치과 마취 부작용","Anesthesia Side Effects","드물게 나타나는 마취 후 증상으로 대부분 일시적입니다.","sleep"),
    ("무통 마취기","Computer-controlled Anesthesia","주입 속도를 제어해 통증을 줄이는 마취 장비입니다.","sleep"),
    ("치료 동의서","Informed Consent","치료 내용·대안·주의사항을 설명하고 동의받는 절차입니다.","surgery"),
    ("진료기록부","Dental Record","진료 내용을 기록·보존하는 법정 문서입니다.","conservative"),
    ("비급여 진료비 고지","Non-covered Fee Disclosure","비급여 항목 비용을 사전 게시하는 제도입니다.","conservative"),
    ("치과 응급상황","Dental Emergency","외상·급성 통증·출혈 등 신속 대응이 필요한 상황입니다.","surgery"),
    ("치아 보관액","Tooth Preservation Medium","빠진 치아를 살리기 위해 담가 오는 보존액(우유 대체 가능)입니다.","surgery"),
    ("재플란테이션 골든타임","Replantation Golden Time","빠진 치아를 다시 심을 수 있는 최적 시간(1시간 이내)입니다.","surgery"),
]

def main():
    path = 'src/data/encyclopedia.json'
    data = json.load(open(path, encoding='utf8'))
    existing = {x['term'] for x in data}
    added = 0
    for term, en, desc, tx in NEW:
        if term in existing:
            continue
        data.append({"term": term, "en": en, "desc": desc, "treatment": tx, "initial": initial(term)})
        existing.add(term)
        added += 1
    json.dump(data, open(path, 'w', encoding='utf8'), ensure_ascii=False, indent=1)
    print(f"added {added}, total {len(data)}")

if __name__ == '__main__':
    main()
